### ISSUE TITLE
Large bucket, s3sync copies no files

### ISSUE THREAD

**Issue by stefanknechtDBE** [larrabee/s3sync#13]
Latest version:
$ ./s3sync --help
Really fast sync tool for S3
Version: 1.14, commit: 418ed115733181f66f235af00e165b3dcf403123, built at: 2019-04-18T14:46:19Z

Command line used:
./s3sync -sk xxx -ss yyy -sr us-west-1 -tk aaa -ts bbb -tr us-west-2 -w 256 -d  s3://foo/ s3://bar/

Tool does nothing:
INFO[0000] Starting sync                                
Synced: 0; Skipped: 0; Failed: 0; Total processed: 0
Avg syncing speed: 0 obj/sec; Avg listing speed: 0 obj/sec
INFO[0001] Sync finished successfully                   
INFO[0001] Synced: 0; Skipped: 0; Failed: 0; Total processed: 0 
INFO[0001] Avg syncing speed:         0 obj/sec; Avg listing speed:         0 obj/sec; Duration:         1 sec

**Comment by stefanknechtDBE** [comment]
Is this not capable of doing folders recursively?

**Comment by larrabee** [comment]
Hello. No, its traversal folders recursively.  
Is `foo` source in your example?  
Try to remove trailing slashes like `s3://foo s3://bar`

**Comment by stefanknechtDBE** [comment]
I see the same result:
INFO[0000] Starting sync                                
Synced: 0; Skipped: 0; Failed: 0; Total processed: 0
Avg syncing speed: 0 obj/sec; Avg listing speed: 0 obj/sec
INFO[0001] Sync finished successfully                   
INFO[0001] Synced: 1; Skipped: 0; Failed: 0; Total processed: 1 
INFO[0001] Avg syncing speed:         1 obj/sec; Avg listing speed:         1 obj/sec; Duration:         1 sec 

There is one single file in the bucket root, and a folder which has tens of thousands of sub-folders in it, on several levels.
It copies the single file, but ignores the folder entirely.

**Comment by stefanknechtDBE** [comment]
There's 28 million files and the tool exits within a second or two. I doubt it's even listing anything recursively.

**Comment by stefanknechtDBE** [comment]
For another test, I chose a single folder along the lines of /foo/a/b/c/d/e and it copied the files within it

But it doesn't seem to want to take anything recursively still.

**Comment by larrabee** [comment]
Can you try s3st engine?  You can use it like this:`s3st://foo s3://bar`.

**Comment by stefanknechtDBE** [comment]
Ohhh now that looks promising:
INFO[0000] Starting sync                                
Synced: 21657; Skipped: 0; Failed: 0; Total processed: 22938
Avg syncing speed: 1805 obj/sec; Avg listing speed: 1911 obj/sec

**Comment by stefanknechtDBE** [comment]
It seems that s3st is working well and quick.
But we do see the tool fail frequently due to connection errors to S3, such as this:
FATA[0286] Listing objects failed: SerializationError: failed to decode REST XML response
        status code: 200, request id: 0x0deadbeef
caused by: read tcp 172.1.2.3:39752->52.219.28.45:443: read: connection reset by peer 

These currently seem to be fatal - is there a way to handle those so that it doesn't fail the entire operation?

**Comment by larrabee** [comment]
Hello.  
Unfortunately is no way to handle this error in `s3st` engine. This error handled correctly in `s3` engine and request is retried.  
Can you build version from `debug` branch and try it with `s3` engine? Im was add more logging to debug your problem.

**Comment by larrabee** [comment]
Fixed in master branch.
