### ISSUE TITLE
Improve package documentation

### ISSUE THREAD

**Issue by jbialy** [larrabee/s3sync#14]
For each of the packages that you have created, i.e., `pipeline`, `collection` and `storage`. Would it be possible for you to improve the documentation as to how each of these could be used? Having comments compatible with godocs would be really nice! I'm looking to build my own cli around the packages you created, very similar to what you have done in .`/cli` except that I'd like to add the ability to push metrics. At this point I'm looking at re-using a lot of your cli code to get this accomplished 😄

**Comment by larrabee** [comment]
Hello.  
It's very nice that my project is useful for you.  
Yep, i can improve documentation, i can start doing it in 1 week.
It would be nice to see your functionality in the pull request;)

**Comment by larrabee** [comment]
I have added basic documentation. Extended documentation will be added later.
