### ISSUE TITLE
Storage class, delete removed options

### ISSUE THREAD

**Issue by archaron** [larrabee/s3sync#15]
Hello!
Very nice project, but I wonder, how can I specify storage class?

In other words, i have something like this for s3cmd:

`s3cmd --storage-class=COLD --delete-removed --acl-private --guess-mime-type --skip-existing 
 sync /backup/ s3://backup/`

Is it possible to reproduce the same action with s3sync?

**Comment by larrabee** [comment]
Hello.
Adding a Storage Class is very simple, I added this function to the master.  
But adding an option `--delete-removed` is very difficult, it does not fit well with the application architecture.
