### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by tailsu** [larrabee/s3sync#18]
I'm syncing a folder that has about 500k objects. A few of these objects are about 1GB each. As soon as s3sync gets to them, it bombs with OOM. The sync ran with 30 workers on an instance with 4GB RAM and no swap.

It would help if the sync streamed file contents instead of reading them wholesale into memory, at least for big files.

**Comment by larrabee** [comment]
Hello. You can use big swap (32-64 Gb or more). 
At this time is impossible to use streamed sync with aws sdk.

**Comment by tailsu** [comment]
The SDK doesn't support object streaming? I find that hard to believe 😸  I mean the AWS CLI streams files back and forth fine, right?

https://docs.aws.amazon.com/sdk-for-go/api/service/s3/

> The Uploader also supports both io.Reader for streaming uploads, and will also take advantage of io.ReadSeeker for optimizations if the Body satisfies that type.

**Comment by larrabee** [comment]
I check the code of s3manager, for io.Reader it's load data by chuck to RAM and create io.ReadSeeker for each chunk.
SDK support streaming, but it requires io.ReadSeeker, but http request returns io.Reader.  
Only way for convert  io.Reader to io.ReadSeeker is copy all content to RAM and create io.ReadSeeker.  
I'll take a closer look at this and maybe do it.

**Comment by fleaz** [comment]
Hi @larrabee,
is this fixed or did you just closed the issue because you don't want to implement this? 
Because we tried your tool at work to sync an customers NAS to S3 but also ran into the same memory issues

**Comment by fleaz** [comment]
Okay. I just saw the 'Limitations' section in the README. I can understand that this is out of scope for this tool. 
Anyway, thanks for the answer.

Best,
Felix
