### ISSUE TITLE
Target parameters ignored

### ISSUE THREAD

**Issue by tirasmuturi** [larrabee/s3sync#20]
Hey, am trying to configure an AWS sync between 2 buckets in different region and this tool only vaidates the source but ignores the target.

am running the command in a bash script.

This is what i run

export TK=TARGETKEY
export TS=TARGETSECRET
export TR=TARGETREGION
export SK=SOURCEKEY
export SS=SOURCESECRET
export SR=SOURCEREGION

./s3sync_bck1 --debug --sync-log --sync-progress --sk $SK --ss $SS --sr $SR --tk $TK --ts $TS --tr $TR -w 128 s3://SOURCEBUCKET s3://TARGETBUCKET

when i run this i get 
INFO[0000] Starting sync                                
DEBU[0001] Listing bucket finished                      
DEBU[0001] Pipeline step: ListSource finished           
DEBU[0001] Pipeline step: LoadObjData finished          
DEBU[0001] Pipeline step: UploadObj finished            
DEBU[0001] Pipeline step: ACLUpdater finished           
DEBU[0001] Pipeline step: Logger finished               
DEBU[0001] Pipeline step: Terminator finished           
DEBU[0001] All pipeline steps finished                  
DEBU[0001] Pipeline terminated                          
INFO[0001] 0 ListSource: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] 1 LoadObjData: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] 2 ACLUpdater: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] 3 UploadObj: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] 4 Logger: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] 5 Terminator: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] Duration: 1.870510625s                       
INFO[0001] Sync Done  

My Bucket have not been synced and if i change the keys for my destination , they have no effect. A correct key and incorrect key gives the same result.

Why is the s3sync not working bearing in mind this is a straight forward setup. Is there anything that am missing that i should know about.

**Comment by larrabee** [comment]
Hello.
This is bug in commit 0b390c. The problem was that the initial S3 prefix for synchronization was not correctly defined. Because of this, no files were included in the synchronization list. This bug was fixed in 2.6 version.

> A correct key and incorrect key gives the same result.
Yep, target storage parameters validating on first file. There are no files for synchronization - there is no validation of the parameters of the storage.

**Comment by tirasmuturi** [comment]
Thanks for your speedy response. Now the sync works for files on the bucket ie. 1st hierarchy objects work perfectly.  if you have folders , the tool throws an exception

this is the stack-trace

INFO[0000] Starting sync                                
DEBU[0001] Listing bucket finished                      
DEBU[0001] Pipeline step: ListSource finished           
DEBU[0003] Recv pipeline err: object: **deploy/test/**  sync error: NoSuchKey: The specified key does not exist.
        status code: 404, request id: A5E3EB8705A49E8D, host id: 07zSPzXfe5h5lGiJyPG/93WDprB7MC1OM1Dp6dZLOa+477nOdAEQQ/qj5564sj7fVVL3uuHE67M= 
ERRO[0003] Sync error: pipeline step: 1 (LoadObjData) failed with error: object: deploy/test/ sync error: NoSuchKey: The specified key does not exist.
        status code: 404, request id: A5E3EB8705A49E8D, host id: 07zSPzXfe5h5lGiJyPG/93WDprB7MC1OM1Dp6dZLOa+477nOdAEQQ/qj5564sj7fVVL3uuHE67M=, terminating 
DEBU[0003] Pipeline step: LoadObjData finished          
DEBU[0003] Pipeline step: ACLUpdater finished           
DEBU[0003] Pipeline step: UploadObj finished            
DEBU[0003] Pipeline step: Logger finished               
DEBU[0003] Pipeline step: Terminator finished           
DEBU[0003] All pipeline steps finished                  
DEBU[0003] Pipeline terminated                          
INFO[0003] 0 ListSource: Input: 0; Output: 18 (6 obj/sec); Errors: 0 
INFO[0003] 1 LoadObjData: Input: 18; Output: 0 (0 obj/sec); Errors: 1 
INFO[0003] 2 ACLUpdater: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0003] 3 UploadObj: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0003] 4 Logger: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0003] 5 Terminator: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0003] Duration: 3.205022461s                       
ERRO[0003] Sync Failed                                  


Thank you for your effort

**Comment by larrabee** [comment]
Can you provide output of this command `s3cmd info s3://<bucket>/deploy/test/`

**Comment by tirasmuturi** [comment]
I had to install s3cmd. This is my stacktrace
<code>
s3://<bucket>/deploy/test/ (object):
   File size: 0
   Last mod:  Thu, 12 Sep 2019 14:45:47 GMT
   MIME type: application/x-directory
   Storage:   STANDARD
   MD5 sum:   d41d8cd98f00b204e9800998ecf8427e
   SSE:       none
   Policy:    b'{"Version":"2012-10-17","Id":"Policy1567521396535","Statement":[{"Sid":"Stmt1567521270541","Effect":"Allow","Principal":{"AWS":"arn:aws:iam::******:root"},"Action":["s3:ListBucket","s3:GetObject"],"Resource":["arn:aws:s3:::<bucket>","arn:aws:s3:::<bucket>/*"]}]}'
   CORS:      none
   ACL:       acl_name: FULL_CONTROL 

</code>

**Comment by larrabee** [comment]
Thank you. I found issue with object with names ended with slash (like your `deploy/test`). Will fix its soon.

**Comment by larrabee** [comment]
I added version 2.7 with fix for this bug.

**Comment by tirasmuturi** [comment]
Thanks so much for your fast response. Lemmi test it out and i give you the feedback.

**Comment by tirasmuturi** [comment]
Hey chief, The package works perfectly. i have a quick question. I have **20TB** of s3 objects i want to sync from one bucket to another bucket. How long do you think it will take me to completely sync the s3 objects. What resources will i need to run the task optimally .Can i dockerize the task such that i can spin up like  300 docker containers for scalability. Please advise.

**Comment by larrabee** [comment]
Hello. 
1. Sync speed depends on you average object size and network bandwidth. By default Amazon have limit around 300-400 requests per second per bucket. So if you have too much small objects you will raise the request limit (You can ask AWS support to increase limits). 
2. Max network bandwidth and RAM. You should have <avg object size> * <workers count> RAM. If you dont have it you can use swap.
3. The tool does not support clustering, but you can run it parallel. For example you have bucket with following structure:
```
/
  dir1/
      ...
  dir2/
      ...
  dir3/
    subdir1/
        ...
    subdir2/
        ...
```
You can run 4 instances of the app. 2 for each directory and 2 for each subdirs.

**Comment by tirasmuturi** [comment]
Thanks you. i will implement your recommendations
