### ISSUE TITLE
OpenBSD: syscall.ENODATA does not exist.

### ISSUE THREAD

**Issue by ClaesBas** [larrabee/s3sync#21]
To get s3sync to work/compile on OpenBSD, you have to replace syscall.ENODATA with syscall.ENOENT in two places in storage/storage-fs.go.

Impressed of speed!
s3cmd in python took me ~45m for 1.2GB and s3sync with 2.4GB made in ~6m (1 cpu & 16 workers)!!

**Comment by larrabee** [comment]
Hello.  
Thanks for the feedback, I'm really glad to hear that the app is useful for you.  

I added beta support for FreeBSD, NetBSD, and OpenBSD. But xattr support is not implemented for OpenBSD, so it will be automatically disabled and will display a warning.  
If you use * BSD systems, please check the application on them.

Tip: it’s normal to use 100-500 workers if your S3 and network are ready for this.
