### ISSUE TITLE
Access denied for S3 bucket where only child objects are only permitted

### ISSUE THREAD

**Issue by tirasmuturi** [larrabee/s3sync#22]
Hi, 

I have a case where i cannot access the PARENT BUCKET but i can list the CHILD OBJECTS.
ie
[root@localhost ~]# s3cmd ls s3://<BUCKETNAME>/DIRECTORY
ERROR: Access to bucket '<BUCKETNAME>' was denied
ERROR: S3 error: 403 (AccessDenied): Access Denied

if i put a trailing slash, i have access to the CHILDREN OBJECTS  in the bucket

[root@localhost ~]# s3cmd ls s3://<BUCKETNAME>/DIRECTORY/
                       DIR   s3://<BUCKETNAME>/DIRECTORY/CONTENT1/
                       DIR   s3://<BUCKETNAME>/DIRECTORY/CONTENT2/
                       DIR   s3://<BUCKETNAME>/DIRECTORY/CONTENT3/
                       DIR   s3://<BUCKETNAME>/DIRECTORY/CONTENT4/
                       DIR   s3://<BUCKETNAME>/DIRECTORY/CONTENT5/
                       DIR   s3://<BUCKETNAME>/DIRECTORY/CONTENT5/

Using this case scenario, when i try to run my s3sync, i get this error since s3://<BUCKETNAME>/DIRECTORY/ is my source bucket. The trailing slash is very important.

This is what i get when i run s3sync
DEBU[0001] S3 listing failed with error: AccessDenied: Access Denied
        status code: 403, request id: 91DF1DF0618DA652, host id: B646GOQYS6s9ISVvTvUJqYjWpBmg91j+vrXGvI9nNzDMZEjdsYT7CCsKV1f9nToaLRTSn+UQR54= 
DEBU[0001] Pipeline step: ListSource finished           
DEBU[0001] Recv pipeline err: AccessDenied: Access Denied
        status code: 403, request id: 91DF1DF0618DA652, host id: B646GOQYS6s9ISVvTvUJqYjWpBmg91j+vrXGvI9nNzDMZEjdsYT7CCsKV1f9nToaLRTSn+UQR54= 
ERRO[0001] Sync error: pipeline step: 0 (ListSource) failed with error: AccessDenied: Access Denied
        status code: 403, request id: 91DF1DF0618DA652, host id: B646GOQYS6s9ISVvTvUJqYjWpBmg91j+vrXGvI9nNzDMZEjdsYT7CCsKV1f9nToaLRTSn+UQR54=, terminating 
DEBU[0001] Pipeline step: LoadObjData finished          
DEBU[0001] Pipeline step: ACLUpdater finished           
DEBU[0001] Pipeline step: UploadObj finished            
DEBU[0001] Pipeline step: Logger finished               
DEBU[0001] Pipeline step: Terminator finished           
DEBU[0001] All pipeline steps finished                  
DEBU[0001] Pipeline terminated                          
INFO[0001] 0 ListSource: Input: 0; Output: 0 (0 obj/sec); Errors: 1 
INFO[0001] 1 LoadObjData: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] 2 ACLUpdater: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] 3 UploadObj: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] 4 Logger: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] 5 Terminator: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0001] Duration: 1.125876588s                       
ERRO[0001] Sync Failed

**Comment by larrabee** [comment]
Hello.
How can i reproduce this behavior?

**Comment by tirasmuturi** [comment]
modify your bucket permissions to a specific bucket such that you only allow access to the child objects.
ie. 

this is the custom bucket policy for my keys

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "ListObjectsInBucket",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::<BUCKETNAME>"
            ],
            "Condition": {
                "StringEquals": {
                    "s3:prefix": [
                        "",
                        "<FOLDER_ACCESS>/",
                        "<FOLDER_ACCESS>/*"
                    ],
                    "s3:delimiter": [
                        "/"
                    ]
                }
            }
        }
    ]
}

**Comment by larrabee** [comment]
I removed prefix cleanup from the code. Now trailing slash will be not removed. But you should remove `s3:delimiter": ["/"]` from the S3 bucket policy (the tool use "flat" listing without delimiter).

**Comment by tirasmuturi** [comment]
Hey,

The binary worked perfectly, thank you for the quick response.

I have a question. if  i run the sync for one hour then i stop it, if i start again will it start from scratch or will it just compare files from source and target then sync files that have not been synced.
