### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tirasmuturi** [larrabee/s3sync#23]
Hey,

I have experienced a memory leak. this is my scenario.
I am syncing 20TB of data from one bucket to another.

The server running the command has 36 CORES 72gb RAM. I am running the following parameters

./s3sync --debug --sync-log --sync-progress --sk $SK --ss $SS --sr $SR --tk $TK --ts $TS --tr $TR -w 768 s3://SOURCEBUCKET/FOLDERACCESS/ s3://TARGETBUCKET

This command runs for a few minutes then after a while the RAM grows exponentially and breaks the command. I would use supervisor to re spawn the task but i would want to know at what point does the binary do garbage collection.

**Comment by larrabee** [comment]
What is the average size of objects in a bucket? The tool copy object content to RAM, so avg memory usage is `<workers count> * <avg object size>`. If you have big objects you can add swap, it's working fine.

**Comment by tirasmuturi** [comment]
I have 768 workers and the average object size is 40mb

**Comment by larrabee** [comment]
You can start with 128 workers, i think for such objects this is enough.

**Comment by tirasmuturi** [comment]
hey, i have tried with the 128 workers, i spinned up my server to have 36 cores 198GB but it took 6 minutes to crash. 

this is the link to the video
https://vimeo.com/user103503535/review/363750563/f9775eee1a

**Comment by larrabee** [comment]
We sync around 10 Tb of data every week and we don't have a memory leak issues. So i think you have big objects, that use too much ram.  Or maybe you have few very big objects.  

You can build program from `debug` branch. With enabled debug (`-d` switch) it will display the synced objects size (in bytes).
