### ISSUE TITLE
Connection reset by peer on s3 -> s3 copy

### ISSUE THREAD

**Issue by 2pvs** [larrabee/s3sync#25]
INFO[0000] Starting sync
ERRO[0500] Sync error: pipeline step: 1 (LoadObjData) failed with error: object: bucket_name/xyz123.tif sync error: read tcp 172.31.31.193:40284->52.216.139.13:443: read: connection reset by peer, terminating
INFO[0500] 0 ListSource: Input: 0; Output: 5000 (10 obj/sec); Errors: 0
INFO[0500] 1 LoadObjData: Input: 5000; Output: 3692 (7 obj/sec); Errors: 1
INFO[0500] 2 ACLUpdater: Input: 3692; Output: 3692 (7 obj/sec); Errors: 0
INFO[0500] 3 UploadObj: Input: 3692; Output: 3657 (7 obj/sec); Errors: 0
INFO[0500] 4 Terminator: Input: 3657; Output: 0 (0 obj/sec); Errors: 0
INFO[0500] Duration: 8m20.697078919s
ERRO[0500] Sync Failed

**Comment by 2pvs** [comment]
The problem above occurs on coping files ~20M each from one s3 bucket to another in one region

**Comment by larrabee** [comment]
Hello.
You can use option `--s3-retry`.
