### ISSUE TITLE
support the point-in-time on a versioned S3 bucket

### ISSUE THREAD

**Issue by urbien** [larrabee/s3sync#3]
@larrabee, would it be possible to add a point in time option to your utility?
we have searched high and low for a good s3 sync. But none do what we need.
- [s3-pit-restore](https://github.com/madisoft/s3-pit-restore ) - supports point in times, but it does not copy s3 object's metadata, and it copies to the local file system and then uploads to s3. So it is slow, expensive and easily will run out of local disk space
- [s3s3mirror](https://github.com/cobbzilla/s3s3mirror) - is doing bucket to bucket, seems to be quite sophisticated in handling large objects and parallelizing but is not doing point time
- [AWS CLI s3 sync](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html?highlight=sync) does not support point time and is reported to be slow, but can do an incremental sync, not just a copy

**Comment by larrabee** [comment]
Hello. Yes it is possible to add support of points in time, but s3sync have few restrictions:
- It is designed for syncing millions of small files. Each object downloaded to RAM on syncing. If you have large objects you should have enough RAM (max RAM usage = max_object_size * worker_count * 5).
- s3sync not copy S3 metadata too (except content-type).
