### ISSUE TITLE
Not able to transfer a file with special character

### ISSUE THREAD

**Issue by semperfitodd** [larrabee/s3sync#30]
/nfs/DS12BayD/Imgsrv/**@juno**/1509/150924XX/1129US00/1129US07/CMP/1129US07_Tag.csv

Not able to sync anything with any special character such as file above.

**Comment by larrabee** [comment]
Hello.  
Thank you for report.
Which error do you have? Can you provide full command line (without keys).

**Comment by semperfitodd** [comment]
./s3sync --tk xxxx --ts xxxxxxxx -w 32 fs:///nfs/DS12BayD/Imgsrv/ s3://cdx-todd-test

INFO[0000] Starting sync
ERRO[0000] Sync error: pipeline step: 1 (LoadObjData) failed with error: object: @juno/1509/150924XX/1129US00/1129US07/CMP/1129US07_Tag.csv sync error: xattr.get /nfs/DS12BayD/Imgsrv/@juno/1509/150924XX/1129US00/1129US07/CMP/1129US07_Tag.csv user.s3sync.meta: operation not supported, terminating
INFO[0000] 0 ListSource: Input: 0; Output: 2 (29 obj/sec); Errors: 0
INFO[0000] 1 LoadObjData: Input: 2; Output: 0 (0 obj/sec); Errors: 2
INFO[0000] 2 ACLUpdater: Input: 0; Output: 0 (0 obj/sec); Errors: 0
INFO[0000] 3 UploadObj: Input: 0; Output: 0 (0 obj/sec); Errors: 0
INFO[0000] 4 Terminator: Input: 0; Output: 0 (0 obj/sec); Errors: 0
INFO[0000] Duration: 68.993936ms
ERRO[0000] Sync Failed

**Comment by larrabee** [comment]
It's not a bug.  
By default s3sync try to read metadata from fs xattr'ibutes. NFS does not support xattr, so you can disable it with flag `--fs-disable-xattr`.
