### ISSUE TITLE
Support specific AWS session token

### ISSUE THREAD

**Issue by JonPeel** [larrabee/s3sync#31]
I'm authenticating with AWS via Okta (saml2) - works fine with the stock aws client but had to tinker on a fork to get this working for s3sync - only issue is right now s3sync always provides a blank third argument for the AWS credentials:

https://github.com/JonPeel/s3sync/commit/574204e9736ecfe3b93c0450a7ada9e68a8a70c8?diff=unified#diff-44bbcc9d983da65f32aa64529eb190e2R45

Commit history here not clean / buggy - just using it to highlight where I needed changes.  Could clean up for a PR - would you want a command line argument (which is the route I went) or some other means or specifying?

Jon

**Comment by larrabee** [comment]
Hello.  
It's looking good. I think `--st` (Source Token) and `--tt` will fine.  
Thank you.

**Comment by larrabee** [comment]
Hello.
This feature was added to master.
