### ISSUE TITLE
Lack of error handler to godirwalk stops sync process

### ISSUE THREAD

**Issue by JonPeel** [larrabee/s3sync#32]
Not all the data I'm syncing is mine; I can view most but occasional hit a permission denied error. The default for godirwalk is to stop the walk it seems.  Can we add an error handler?  Might need a bit more thinking about than the below quick change

https://github.com/JonPeel/s3sync/commit/3dad8512f0f76c6b7dee1b29c6ca186ac3773e57

Jon

**Comment by larrabee** [comment]
Hello.  
I wrote [first draft](https://github.com/larrabee/s3sync/commit/8fa730a56e9766b45e0bfd8b01e28e97162114c3) of this function.  
It's implements error handling logic, but it's not final.

**Comment by larrabee** [comment]
This enhancement added to master branch.
