### ISSUE TITLE
Access denied on attempt to copy file from local fs to s3

### ISSUE THREAD

**Issue by 2pvs** [larrabee/s3sync#35]
level=error msg="Sync error: pipeline step: 3 (UploadObj) failed with error: object: aaa.xml sync error: AccessDenied: Access Denied\n\tstatus code: 403, request id: 57064C841C470CAA, host id: iOGzu8d04mtG5r8U4+IACYtpkFcywDBn0BmRB/mP06mXhunPYsqWux3j9tO0GXD5AFBV2G2PxOg=,

the error occur in my docker container running s3sync binary from command line. I can complete the copy operation by aws s3 sync on the same objects, but s3sync fails. It seems all the permissions are in place...

**Comment by larrabee** [comment]
Hello.  
Can you write full cmd line (without keys)?

**Comment by 2pvs** [comment]
it looks like this, just replaced folder names:

./s3sync -w 128 fs://localfolder1/localfolder2/ s3://mybuckethere/subfolder1/subfolder2/subfolder3/

**Comment by larrabee** [comment]
Are you properly define target key (`--tk`), target secret (`--ts`) and bucket region `--tr`?

**Comment by 2pvs** [comment]
I do not use these params due to the following:
- The container task runs under the IAM role with correct permissions, and they work 100% (as I mentioned, "aws s3 sync" works)
- The bucket region is default us-east-1

**Comment by larrabee** [comment]
Do you have credentials file `$HOME/.aws/credentials`? If yes try to rename it.

**Comment by 2pvs** [comment]
I do not use aws credentials in the docker container, since it is not good security practice. It runs under iam role. Please let me know, if s3sync does not support execution under iam role, I will use aws cli in this case. Anyway, this option is worth to implement.

**Comment by larrabee** [comment]
Hello. This bug should be fixed in version `2.14 `.  
Please try it and report the result.;)

**Comment by 2pvs** [comment]
Yes, it works now!
Many thanks!
