### ISSUE TITLE
sync header info when sync s3 to s3

### ISSUE THREAD

**Issue by rchaser53** [larrabee/s3sync#36]
Can I also sync Content-Type when I sync S3 to S3 like ```aws s3 sync```?

**Comment by larrabee** [comment]
Hello.  
`Content-Type` and other file metadata (like `Content-Disposition` and etc) syncing automatically.

**Comment by rchaser53** [comment]
Really? I will confirm it at my company tomorrow. Thank you.

**Comment by rchaser53** [comment]
It works. Great! I close this issue. Thanks a lot!
