### ISSUE TITLE
Files copied over empty?

### ISSUE THREAD

**Issue by jonathon2nd** [larrabee/s3sync#39]
Using s3sync to copy items to a new ceph cluster. Items being copied over are empty. I can get them and download them locally, but they are empty.

I have tried using wasabi and another ceph cluster as source.

Thoughts?

**Comment by larrabee** [comment]
Hello.
Can you provide your cmd line (without keys)?
What version of s3sync are you use?

**Comment by jonathon2nd** [comment]
Pulled and built master.

./s3sync --tk XXX --ts XXX --sk XXX --ss XXX --se "wasabi.endpoint.example.com" --te "new.ceph.example.com" -w 128 s3://backup-pbs s3://pbs_3 --s3-acl authenticated-read --workers 8 --sync-progress --sync-log --debug

Same results if the old ceph cluster is the sourse.

**Comment by jonathon2nd** [comment]
It appears our issue is related to cloudflare. Not sure why yet, but it works when we replace the endpoint with the ip.

**Comment by larrabee** [comment]
Sory, im checking the latest changes and find a bug in S3 PutObject funcion.
Please try a latest version from master.
