### ISSUE TITLE
Destructive Sync?

### ISSUE THREAD

**Issue by starrett67** [larrabee/s3sync#41]
I would love to be able to destroy files that do not exist in the source. I have a need to sync a large number of files but also clean up old files. So far this is the fastest tool I have found I just wish there was a destructive option. 

I am thinking about learning some go so I can implement it myself but that would take a long time.

**Comment by larrabee** [comment]
Hello.
Full synchronization (destructive) and fast mutually exclusive. With destructive synchronization, you need to create a complete list of files in the source and in the target and diff them. For large buckets, this is a long time.  
This is not the main user case for my program, I am not aimed at fulfilling all possible synchronization options, but at fast synchronization.  

In your case, I would suggest splitting the operation into 2 stages:
* Upload all files from source to target
* Write a script that will list buckets and save the listing to a file. After that, you will need to compare these lists and delete the files that are in list 2 but not in the list 1. You can write the script on any language, not necessarily golang.

**Comment by patsevanton** [comment]
Good feature. It is sad that it is not supported.
