### ISSUE TITLE
Has this been tested on Windows yet?

### ISSUE THREAD

**Issue by sgprabhash** [larrabee/s3sync#42]
I tried to build it on windows.
the EXE builds fine, but when trying sync a local dir (with sub dirs), the FS path is not able to locate any files on the local file system.

`s3sync --tk zz--ts yyyy-w 128 fs://e:/some/path/ s3://bucket-in-s3/path/ `
the error i get is 

`sync error: open e:\\some\\path\\e:\\some\\path\\folder\\somefile.pdf: The filename, directory name, or volume label syntax is incorrect., terminating
`
see how the path is appended twice...

What am I doing wrong?

**Comment by larrabee** [comment]
Hello.
It's wrote for UNIX systems. I'm used UNIX-specific features, path separators and etc.  
All this can be fixed and then it should work under Windows, but it's a lot of work. I'm not sure that using under Windows is a very necessary case.  
Anyway, you can use the app through Cygwin or WSL.
