### ISSUE TITLE
--debug and --sync-log do not provide any output

### ISSUE THREAD

**Issue by pdezwart** [larrabee/s3sync#43]
Syncing from S3 to Ceph using the following command. The result does not print any meaningful debug or sync log. Note that the DEBUG output only shows up after letting the command run for a little before SIGINT. This has been tried without progress bar as well. Tested on both Linux and Mac with identical results:

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.5
BuildVersion:	19F101
```

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"
```

```
s3sync --sync-log --debug -p --filter-modified --tk REDACTED --ts REDACTED --sk REDACTED --ss REDACTED --te 'http://ceph.internal:8080' -w 12 s3://folder/daydate=2020-06-13/ s3://folder/daydate=2020-06-13/```
INFO[0000] Starting sync                                
  WARN[0017] Receive signal: interrupt, terminating       
DEBU[0019] Pipeline step: ListSource finished           
DEBU[0022] Pipeline step: FilterObjectsModified finished 
DEBU[0022] Pipeline step: LoadObjData finished          
DEBU[0022] Pipeline step: UploadObj finished            
DEBU[0022] Pipeline step: Logger finished               
DEBU[0022] Pipeline step: Terminator finished           
DEBU[0022] All pipeline steps finished                  
DEBU[0022] Pipeline terminated                          
INFO[0022] 0 ListSource: Input: 0; Output: 7000 (308 obj/sec); Errors: 0 
INFO[0022] 1 FilterObjectsModified: Input: 7000; Output: 0 (0 obj/sec); Errors: 0 
INFO[0022] 2 LoadObjData: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0022] 3 UploadObj: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0022] 4 Logger: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0022] 5 Terminator: Input: 0; Output: 0 (0 obj/sec); Errors: 0 
INFO[0022] Duration: 22.756570531s                      
WARN[0022] Sync Aborted 
```

The Ceph version is Mimic, which does not support ListObjectsV2 (has been a constant source of frustration). There may be other APIs that are not fully/properly supported that _might_ be causing issues.

**Comment by pdezwart** [comment]
I was able to get this to work when building from trunk... But I ran into another issue, where it would cycle over the first 1k files in an AWS source bucket. I implemented ListObjectsV2 which fixed the problem, so I am running off of a custom binary. At this point, I have to assume that there are ghosts in the machine, closing issue.

**Comment by larrabee** [comment]
Hello.  
1. Debug log print only errors (S3 or FS). Some of this errors can be invisible in normal mode (because re-query solved the problem).
2. Sync log print only synced files and not print skipped files.
3. We use this tool for backup Ceph. ListObjectsV2 with Mimic working fine.  
4. The first message shows that all the files did not go through the `FilterObjectsModified` filter.
5. ` where it would cycle over the first 1k files in an AWS source bucket` - can you tell more about the problem?
