### ISSUE TITLE
TCP Connection closed

### ISSUE THREAD

**Issue by manojrajpurohit** [larrabee/s3sync#44]
Built the program using "go build"
Requirement was to sync around 7 GB of data from one s3 bucket to other. 
Started sync using below command

./s3sync --sk "<source_key>" --ss "<source_secret>" --st "<source_token>" --tk "<taregt_key>" --ts "<target_secret>" --tt "<target_token>" -w 128 s3://<source_bucket_name>/<prefix> s3://<target_bucket_name>/<prefix>

the sync was running and after a while it stopped with error message. 
"tcp connection closed"

**Comment by larrabee** [comment]
Hello.  
Due to some reasons your server close the connection.  
You can check server logs for errors.  
For avoid this problem you can add to s3sync this option: `--s3-retry 3 `. It's control how many retries the program will do on error.
