### ISSUE TITLE
sync error: InvalidURI: Couldn't parse the specified URI.

### ISSUE THREAD

**Issue by ferrettinico** [larrabee/s3sync#45]
I get the following output/error on certain filenames which contain special characters:

INFO[0000] Starting sync                                
ERRO[0027] Sync error: pipeline step: 2 (UploadObj) failed with error: object: B�IBHIN GALLAGHER_Certificate_of_Achievement_653192.pdf sync error: InvalidURI: Couldn't parse the specified URI.

**Comment by larrabee** [comment]
Hello.  
Please provide you cmd line (without keus of course).

**Comment by ferrettinico** [comment]
./s3sync -tk XXXXXXXX -ts YYYYYYYYYY --workers 2
../../../ssssssssssssssss/files/pdf_certificates
s3://uuuuuuuuuuuuuuuuuuuuuuuuuu/pdf_certificates/

**Comment by ferrettinico** [comment]
same cmd line  works with directories that doesn't have files with
irregular characters on the name

**Comment by larrabee** [comment]
Hello.
The error `InvalidURI: Couldn't parse the specified URI.` is AWS server error.  
It's look like server cannot decode some UTF8 characters. So only way to solve it - rename file.
