### ISSUE TITLE
Raspberry Pi Distributable?

### ISSUE THREAD

**Issue by timendez** [larrabee/s3sync#46]
Hey there,

I'm trying to migrate a cronjob from my OSX laptop to my Pi, but am running into the classic `cannot execute binary file: Exec format error` from which the Pi suffers from time to time.

I tried to build from source (and tried to use docker), but am getting errors with my Go installation. Those errors aren't tied to s3sync, but I can't compile Golang on my rbpi - with all signs pointing to a reinstall of Ubuntu, which I'd strongly like to avoid.

My Raspberry Pi is the 3b+ with aarch64.

Thanks!

**Comment by larrabee** [comment]
Hello.  
Added builds for ARM. For RPi, you need `Linux arm64` build.

**Comment by timendez** [comment]
Absolutely floored with the fast response time, `s3sync_2.21_Linux_arm64.tar.gz` worked flawlessly on my Raspberry Pi.

Thank you so much!!!
