### ISSUE TITLE
Question about sync

### ISSUE THREAD

**Issue by gkyildirim** [larrabee/s3sync#48]
Hi,

Thanks for sharing this tool. It looks great!

One of my collegue used s3sync. What he observed that it is very fast! But it takes equal amount of time to sync if the copy process is somehow canceled. For example it takes 1/2 hour to copy 900.000 out of 1million objects. When copy is canceled, s3sync takes another 1/2 hour to compare 900.000 objects and copies 100.000 left.

Would you mind if I ask whether we are missing something here?

Thanks for your time.

**Comment by larrabee** [comment]
Hello.
Thank you, it's nice that my work helped you.  
  
You are right, the tool doesn't save sync progress between runes.  
First full synchronization should be completed anyway.  
For next runes you can do incremental sync only for new files with `--filter-after-mtime`.

**Comment by gkyildirim** [comment]
Thanks for the information
