### ISSUE TITLE
x509: certificate signed by unknown authority, terminating

### ISSUE THREAD

**Issue by Robin021** [larrabee/s3sync#49]
I try this command in aws China region but got certificate issue: 
`docker run --rm -ti larrabee/s3sync  --tk xxxxxx --ts xxxxxxxxxxxxxx --sr cn-northwest-1 --tr cn-north-1 --sk xxxxx --ss xxxxxxx -w 128 s3://s3-service-dev/folder/ s3://s3-dev-rawdata/csv/cpoc/s3-service-dev/ `

ERRO[0000] Sync error: pipeline step: 0 (ListSource) failed with error: RequestError: send request failed
caused by: Get https://s3.cn-northwest-1.amazonaws.com.cn/s3-service-dev?encoding-type=url&max-keys=1000&prefix=s3-service-dev%2F**:x509: certificate signed by unknown authority, terminating**

Is this good tools support China region please ?

**Comment by larrabee** [comment]
Hello. It's a bug with missing ca-certificates in docker image.
Fixed in 2.27 release.
