### ISSUE TITLE
Errors in copying large buffers

### ISSUE THREAD

**Issue by kenshiro75** [larrabee/s3sync#50]
hi,

i'm getting strange errors while trying to sync files from a very large bucket (~300Gb) : 

during the sync process , it seems that very often s3sync creates a phantom file into the local fs with the same path and name of a bucket subdir (?) : this file is not present in the bucket.

this behaviour makes s3sync unable to copy the files into the destination's directory because there is already a file named as the dir itself.... 
below are the recursive logs that i'm getting for all the files in the /lots_img/ subfolder .

```
WARN[7141] Failed to sync object: /lots_img/7/501/810.jpg, error: mkdir /home/media/lots_img/7: not a directory, skipping 
DEBU[7141] Recv pipeline err: object: /lots_img/7/503/146.jpg sync error: mkdir /home/media/lots_img/7: not a directory 
...
```
this is the command i used to sync from the s3 bucket :
`./s3sync -p -d -f skip --sk <key> --ss <secret> --sr <region> -w 128 s3://<bucket> fs:///<folder>`

thank you in advance,
Ken

**Comment by larrabee** [comment]
Hello.
It's not a "phantom files".  S3 does not have directories, only objects. So in S3 you can create 2 object like this:
- `abc/`
- `abc/asd`
And for S3 it's two different objects.
But when you synchronize files on FS, s3sync creates an `abc` file, and then tries to create a` abc/ `directory for the` abc / asd` file, which of course fails.  
  
I wrote simple filters for this case, it's added to 2.28 version. You can use it with `--filter-not-dirs` or `--filter-dirs`. See cli help details.
