### ISSUE TITLE
MacOS arm64 build?

### ISSUE THREAD

**Issue by orenwolf** [larrabee/s3sync#51]
Hello!

First, thank you so much for providing s3sync! It fills a particular but significant niche for those of us that can't make use of the awscli "copy" command for whatever reason - either because the selection criteria are too coarse or, as in our case, because we are moving resources between s3 and other technologies, such as ceph.

One request for your releases, can you provide an arm64 release for macOS as well?

Thanks again!

**Comment by cl-bvl** [comment]
Hello.  
Thank you;)  
MacOS arm64 build available from version 2.29.

**Comment by orenwolf** [comment]
Thanks so much!
