### ISSUE TITLE
Any chance of existing file on FS getting overwritten with incomplete content after sync

### ISSUE THREAD

**Issue by evisong** [larrabee/s3sync#52]
Hi,

`s3sync` is super impressive to me regarding its speed and active maintenance, thanks for open-sourcing this tool. 

https://github.com/larrabee/s3sync/blob/44119b3d83f305d1ff3ef2e8a6bd81d665573a21/storage/fs/fs.go#L138

According to this line, I'm thinking of the following use case:

- Sync target: an existing file on FS, e.g. a 100MB CSV file, 
- Sync source: a new version of the file above on S3, e.g. 101MB CSV file;

When syncing starts, the target 100MB file on FS is truncated to 0 bytes at the beginning. And then, is there any chance the following cases happen after syncing?

1. `io.Copy()` fails for some reason, the target file remains at 0 bytes.
2.  Assume the FS hardware is very very slow when writing, end-user reads the target file before `io.Copy()` finishes its job, then he only gets partial content unexpectedly, e.g. 50MB of 101MB.

Thanks.

**Comment by cl-bvl** [comment]
Hello.  
You are right, User may encounter a partially written file.  
Possible solution - write to temporary file and switch files with `mv`.

**Comment by cl-bvl** [comment]
I added option `--fs-atomic-write` for version `2.30`.

**Comment by evisong** [comment]
It's great! Thanks for the fast response. This `--fs-atomic-write` is indeed a key feature to me, I'll try it right now.

I'm closing this for now.
