### ISSUE TITLE
filter-not-exist really slows down sync

### ISSUE THREAD

**Issue by jorkzijlstra** [larrabee/s3sync#56]
I'm trying to get the s3sync to upload non existing files at a reasonable speed. 

```
s3sync --tk "$AWS_ACCESS_KEY_ID" --ts "$AWS_SECRET_ACCESS_KEY" --tt "$AWS_SESSION_TOKEN" --tr "us-west-2"  --filter-not-exist -w 128 -p /source/Small/ s3://bucket/Small/
```

Adding the ` --filter-not-exist` option will cause the images processed to drop from ~150 - 200 objects/sec to just 5 objects/sec. I get that you now need to do an object exists check on the s3. Increasing the -w does seem to help. Is there any way to speed thing up?

**Comment by cl-bvl** [comment]
Hello, this is a known flaw in this filter. It usually doesn't degrade performance as much as it does yours.
The best way to speed up is not to use it.
You can do a full sync, and then sync only the diff, like this:
```
# Get current date as unix timestamp
>> date +%s                                                                                                                                                                2 ↵
1623002481
# Start full sync
>> s3sync --tk "$AWS_ACCESS_KEY_ID" --ts "$AWS_SECRET_ACCESS_KEY" --tt "$AWS_SESSION_TOKEN" --tr "us-west-2" -w 128 -p /source/Small/ s3://bucket/Small/
# Start diff sync. Only files that have changed since the last sync will be synced.
>> s3sync --tk "$AWS_ACCESS_KEY_ID" --ts "$AWS_SECRET_ACCESS_KEY" --tt "$AWS_SESSION_TOKEN" --tr "us-west-2" -w 128 -p /source/Small/ s3://bucket/Small/ --filter-after-mtime 1623002481
```

**Comment by jorkzijlstra** [comment]
@cl-bvl 

Thanks for the suggestion. Using the `filter-after-mtime` inspects only the metadata of the local files and does not require S3 lookups so it makes sense that it would be way faster.
