### ISSUE TITLE
error: EntityTooLarge: Your proposed upload exceeds the maximum allowed size

### ISSUE THREAD

**Issue by lhdo** [larrabee/s3sync#62]
Maximum upload size for S3 seems to be limited to 5GB. For now, I am skipping these files. Any way to get s3sync to sync files larger than 5GB?

**Comment by cl-bvl** [comment]
Hello. 
The method for uploading large files is quite different from the usual one, so I did not implement it. You can use aws cli or s3cmd to upload large files. They are quite effective when dealing with a small number of large files.
