### ISSUE TITLE
Don't sync files that haven't changed

### ISSUE THREAD

**Issue by jbialy** [larrabee/s3sync#7]
It seems that the current implementation doesn't do any metadata checking between the source and destination objects? Objects that haven't changed at the `source` shouldn't have to be transferred to the destination, especially when dealing with large data files. 🤔

**Comment by larrabee** [comment]
Hello.
Filtering by ETag are added to master branch.  
Initial copy should be created with the s3sync with enabled xattr future. (ETags will saved to FS xattr.) 
All subsequent launches of synchronization with the key `--filter-modified` will synchronize only the changed files.

**Comment by jbialy** [comment]
Just compiled the master branch and I get a seg violation 😢 

```
./s3sync
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1080a79]

goroutine 1 [running]:
os.(*File).Name(...)
	/usr/local/Cellar/go/1.12.7/libexec/src/os/file.go:50
github.com/pkg/xattr.fsetxattr(...)
	/Users/cqd/go/pkg/mod/github.com/pkg/xattr@v0.4.1/xattr_darwin.go:48
github.com/pkg/xattr.FSet(0x0, 0x10b2ead, 0x10, 0xc00007af7a, 0x6, 0x6, 0xc0000721b0, 0x1080d6f)
	/Users/cqd/go/pkg/mod/github.com/pkg/xattr@v0.4.1/xattr.go:123 +0x29
main.main()
	/Users/cqd/github/s3sync/test.go:10 +0x9e
```

**Comment by larrabee** [comment]
I forgot to remove file `test.go` from project root. You can pull changes and build it with command `go build -o s3sync ./cli`

**Comment by jbialy** [comment]
Awesome, thank you!
