### ISSUE TITLE
Panic syncing from S3 to local FS

### ISSUE THREAD

**Issue by webfrank** [larrabee/s3sync#89]
INFO[0000] Starting sync                                
INFO[0001] Sync file                                     Content-Type=image/jpeg key=weapons/DSC_0001.JPG size=1127801
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8d87e6]

goroutine 83 [running]:
github.com/larrabee/s3sync/pipeline/collection.glob..func17(0x0?, 0x0?, 0xc00004c7d0?, 0x4fb4d6?, 0x1034030?)
	/home/larrabee/Work/opensource/s3sync/pipeline/collection/misc.go:32 +0x346
github.com/larrabee/s3sync/pipeline.startWorkers.func1(0x3)
	/home/larrabee/Work/opensource/s3sync/pipeline/main.go:140 +0x89
created by github.com/larrabee/s3sync/pipeline.startWorkers
	/home/larrabee/Work/opensource/s3sync/pipeline/main.go:136 +0x3a

**Comment by cl-bvl** [comment]
Thanks, fixed.
