### ISSUE TITLE
README: offers streaming or limited to files fitting in RAM?

### ISSUE THREAD

**Issue by nickmellor** [larrabee/s3sync#90]
1. Tool offers streaming sync (Examples section):

    Use streaming S3 transfers (reduces memory, might be slower for small files):

    `s3sync --sk KEY --ss SECRET --tk KEY --ts SECRET -w 128 s3s://shared/test/ s3s://shared_new`

_CONTRADICTS(?)_

2. Limitations Section:

    each object is loaded into RAM

Which of these is actually true?

**Comment by cl-bvl** [comment]
Add note to readme.
