### ISSUE TITLE
s3.ListObjects maybe cause an infinite loop

### ISSUE THREAD

**Issue by jeessy2** [larrabee/s3sync#91]
In some coditions, Using `ListObjectsPagesWithContext` will cause an infinite loop. But when i change to `ListObjectsV2PagesWithContext` and it works fine.

`ListObjectsPagesWithContext` getting next marker always some. There is some logs:
```
encoding-type=url&marker=equipxxx1692601065139.pdf%255Bminio_cache%253Av2%252Creturn%253A%255D&max-keys=1000&prefix=
encoding-type=url&marker=equipxxx1692601065139.pdf%255Bminio_cache%253Av2%252Creturn%253A%255D&max-keys=1000&prefix=
encoding-type=url&marker=equipxxx1692601065139.pdf%255Bminio_cache%253Av2%252Creturn%253A%255D&max-keys=1000&prefix=
```

my env: 
 - minio latest 
 - about 6k files, 26GB

**Comment by cl-bvl** [comment]
Thank you.
Switched to ListObjectsV2PagesWithContext
